name: "patch-release-me"
version: "0.3.1"
repository: "42ByteLabs/patch-release-me"

locations:
  - name: "Actions Docs"
    paths:
      - 'README.md'
      - '.github/workflows/*.yml'
      - 'actions/Dockerfile'
    patterns:
      # Actions
      - '42ByteLabs/patch-release-me@([0-9]\.[0-9]\.[0-9])'
      # Containers
      - 'ghcr.io/42bytelabs/patch-release-me:([0-9]\.[0-9]\.[0-9])'

