name: "patch-release-me"
version: "0.3.1"
repository: "42ByteLabs/patch-release-me"

ecosystems:
  - Rust

locations:
  - name: "Actions Docs"
    paths:
      - 'README.md'
      - '.github/workflows/*.yml'
      - 'actions/Dockerfile'
    patterns:
      # Actions
      - '{repository}@{version}'
      # Containers
      - 'ghcr.io/{repository}:{version}'

