name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  project:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/project.yml
    uses: 42ByteLabs/.github/.github/workflows/project.yml@main
    secrets: inherit

  cargo-publish:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-publish.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-publish.yml@v0.12
    if: ${{ needs.project.outputs.release == 'true' }}
    needs: [ project ]
    secrets: inherit
    with:
      crate: patch-release-me

  cargo-binaries:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-binaries.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-binaries.yml@v0.12
    if: ${{ needs.project.outputs.release == 'true' }}
    needs: [ cargo-publish ]
    secrets: inherit
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      version: ${{ needs.project.outputs.version }}
      crate: patch-release-me

  container-publish:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/container.yml
    uses: 42ByteLabs/.github/.github/workflows/container.yml@v0.12
    if: ${{ needs.project.outputs.release == 'true' }}
    needs: [ project ]
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      security-events: write
    with:
      version: ${{ needs.project.outputs.version }}
      container-name: "42bytelabs/patch-release-me"

