name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        type: string
        required: true

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  cargo-publish:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-publish.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-publish.yml@v0.8
    secrets: inherit
    with:
      crate: patch-release-me

  docker-release:
    # https://github.com/42ByteLabs/.github/tree/main/.github/workflows/container.yml
    uses: 42ByteLabs/.github/.github/workflows/container.yml@v0.8
    secrets: inherit
    with:
      version: '${{ inputs.version }}'
