name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cargo-publish:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-publish.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-publish.yml@v0.10
    secrets: inherit
    with:
      crate: patch-release-me

  container-publish:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/container.yml
    uses: 42ByteLabs/.github/.github/workflows/container.yml@main
    needs: [ cargo-publish ]
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
