name: "Test Action"

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: read

jobs:
  action-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Run Action"
        uses: 42ByteLabs/patch-release-me@0.6.0

