name: "Test Action"

on:
  push:
    branches: ["main"]

jobs:
  action-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Run Action"
        uses: 42ByteLabs/patch-release-me@v0.1.0

